image: archlinux
packages:
  - cmake
  - extra-cmake-modules
  - qt5-quickcontrols2
  - kirigami2
  - kcoreaddons
  - ki18n
  - kconfig
  - qtkeychain-qt5
  - quazip-qt5
  - rust
  - unshield
  - gamemode
  - reuse
  - flatpak-builder
sources:
  - https://git.sr.ht/~redstrate/astra
tasks:
  - reuse: |
      cd astra
      reuse lint
  - configure: |
      cd astra
      cmake -S . -B build-cmake
  - build: |
      cd astra
      cmake --build build-cmake
  - flatpak: |
      cd astra
      flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      flatpak install --user -y runtime/org.kde.Platform/x86_64/5.15-22.08 runtime/org.kde.Sdk/x86_64/5.15-22.08 org.freedesktop.Sdk.Extension.rust-stable/x86_64/22.08 
      flatpak-builder build --user --force-clean zone.xiv.astra.yml 
      flatpak build-export export build
      flatpak build-bundle export astra.flatpak zone.xiv.astra --runtime-repo=https://flathub.org/repo/flathub.flatpakrep
artifacts:
  - astra/build-cmake/bin/astra
  - astra/astra.flatpak