image: archlinux
packages:
  - cmake
  - extra-cmake-modules
  - qt6-quickcontrols2
  - qt6-webengine
  - kirigami2
  - kcoreaddons
  - ki18n
  - kconfig
  - qtkeychain-qt6
  - quazip-qt6
  - rust
  - unshield
  - gamemode
  - reuse
  - flatpak-builder
sources:
  - https://git.sr.ht/~redstrate/astra
tasks:
  - reuse: |
      cd astra
      reuse lint
  - tarball: |
      cd astra
      ./scripts/tarball.sh
  #- configure: |
  #    cd astra
  #    cmake -S . -B build-cmake
  #- build: |
  #    cd astra
  #    cmake --build build-cmake
  #- flatpak: |
  #    cd astra
  #    ./build-flatpak.sh
artifacts:
  - astra-source.tar.gz
#  - astra/build-cmake/bin/astra
#  - astra/astra.flatpak