image: archlinux
packages:
  - cmake
  - extra-cmake-modules
  - qt5-quickcontrols2
  - qt5-webengine
  - kirigami2
  - kcoreaddons
  - ki18n
  - kconfig
  - qtkeychain-qt5
  - quazip-qt5
  - rust
  - unshield
  - gamemode
  - reuse
  - flatpak-builder
sources:
  - https://git.sr.ht/~redstrate/astra
tasks:
  - reuse: |
      cd astra
      reuse lint
  - configure: |
      cd astra
      cmake -S . -B build-cmake
  - build: |
      cd astra
      cmake --build build-cmake
  - flatpak: |
      cd astra
      ./build-flatpak.sh
artifacts:
  - astra/build-cmake/bin/astra
  - astra/astra.flatpak