image: archlinux
packages:
  - cmake
  - extra-cmake-modules
  - qt6-quickcontrols2
  - qt6-webengine
  - kirigami2
  - kcoreaddons5
  - ki18n5
  - kconfig5
  - qtkeychain-qt6
  - quazip-qt6
  - rust
  - unshield
  - gamemode
  - reuse
  - flatpak-builder
  - rsync
sources:
  - https://git.sr.ht/~redstrate/astra
secrets:
  - b748582a-5d31-4fe8-94d6-4a63035e97aa
tasks:
  - reuse: |
      cd astra
      reuse lint
  - tarball: |
      cd astra
      ./scripts/tarball.sh
  - upload-tarball: |
      echo "StrictHostKeyChecking=no" >> ~/.ssh/config
      rsync -e 'ssh -p 38901' -Wvr astra-source.tar.gz deploy@ryne.moe:/srv/http/astra-distrib/astra/git/
  #- configure: |
  #    cd astra
  #    cmake -S . -B build-cmake
  #- build: |
  #    cd astra
  #    cmake --build build-cmake
  #- flatpak: |
  #    cd astra
  #    ./build-flatpak.sh
artifacts:
  - astra-source.tar.gz
#  - astra/build-cmake/bin/astra
#  - astra/astra.flatpak
